server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/library_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

logging:
  file:
    name: logs/booksbase.log
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
    com.vma.bookbase: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true


